# Generated by Django 4.0.4 on 2022-04-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_skill_user_country_user_dob_user_location_user_nrc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='skill',
        ),
    ]
