# Generated by Django 4.0.4 on 2022-04-12 19:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_remove_user_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=900)),
                ('script', models.TextField(blank=True, default=None)),
                ('slug', models.SlugField(default=None)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert0', models.FileField(blank=True, default=None, upload_to='user/skills/')),
                ('cert1', models.FileField(blank=True, default=None, upload_to='user/skills/')),
                ('cert2', models.FileField(blank=True, default=None, upload_to='user/skills/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='acc.service')),
                ('worker', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='userrating',
            name='skill',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='acc.userskill'),
        ),
        migrations.AddField(
            model_name='userrating',
            name='worker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userrating',
            constraint=models.CheckConstraint(check=models.Q(('rate__range', (0, 10))), name='valid_rate'),
        ),
        migrations.AddConstraint(
            model_name='userrating',
            constraint=models.UniqueConstraint(fields=('worker', 'skill'), name='rating_once'),
        ),
    ]
