# Generated by Django 4.0.4 on 2022-04-12 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0004_service_userrating_userskill_delete_skill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.TextField(blank=True, default=None)),
                ('ammount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='userrating',
            name='rating_once',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='worker',
        ),
        migrations.AddField(
            model_name='userrating',
            name='service_provider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='service_provider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrating',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userrating',
            constraint=models.UniqueConstraint(fields=('user', 'skill'), name='rating_once'),
        ),
        migrations.AddField(
            model_name='usercontract',
            name='contractor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contractor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercontract',
            name='skill',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='acc.userskill'),
        ),
        migrations.AddField(
            model_name='usercontract',
            name='worker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='worker', to=settings.AUTH_USER_MODEL),
        ),
    ]
